apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-eptj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-eptj
    app.kubernetes.io/part-of: build-suite-test-application-xjrf
  name: devfile-sample-hello-world-eptj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-eptj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-eptj
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-mqtu-tenant/build-suite-test-application-xjrf/devfile-sample-hello-world-eptj@sha256:40e4d84c064d6188f66bbdaff5f788dee2af749e89cd1879c1d1de69654acdc1
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
